main: net.urbanmc.ezauctions.EzAuctions
name: ezAuctions
version: 1.0
authors: [Elian, Silverwolfg11]
description: AuctionCommand plugin based off of floAuction
softdepend: [Vault]

commands:
  ezauctions:
    description: Auctions command
    aliases: [ezauction, auctions, auction, auc]
  bid:
    description: Bid on an auction
