main: net.urbanmc.ezauctions.EzAuctions
name: ezAuctions
version: 1.0
authors: [Elian, Silverwolfg11]
description: A simple, text-based auction plugin
softdepend: [Vault]

commands:
  auction:
    description: Auctions command
    aliases: [ezauctions, ezauction, auctions, auc]
  bid:
    description: Bid on an auction
    aliases: [b]
