name: Automatically create release with artifact on pull request

on:
  pull_request:
    branches: [ 'master' ]
    types: [ closed ]

jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # set up jdk 1.8
      - uses: actions/setup-java@v1
        with:
          java-version: 1.17

      # download latest buildtools and get remapped spigot jar
      - run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - run: java -jar BuildTools.jar --rev 1.18 --remapped

      # build jar with maven
      - run: mvn --batch-mode --update-snapshots verify

      - name: Create Release
        uses: softprops/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: false
          prerelease: false
          # Release name will default to tag name
          # Tag name will be the name of the branch
          tag_name: ${{ github.head_ref }}
          files: "./target/ezAuctions*-SNAPSHOT.jar"
          fail_on_unmatched_files: true
