name: build

on:
  workflow_dispatch:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # We need to checkout all tags for the version to be calculated correctly
      - name: Checkout with all tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # set up jdk 1.17
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      # build jar with maven
      - name: Build Project
        run: mvn --batch-mode --update-snapshots verify

      - name: Upload jar to workflow run
        uses: actions/upload-artifact@v4
        with:
          name: ezAuctions.jar
          path: target/ezAuctions.jar
